// This is a list of projects from my original Google Doc

exports.projectTitles = [
  "Arrival (Deluxe) - ABBA***p",
  "R.I.P. - Actress***e",
  "Back 2 Ballin - Adamn Killa***h",
  "Fuck Your Expectations Pt. 2 - AG Club***h",
  "Apple - A. G. Cook***e",
  "7G***e",
  "Apple vs. 7G***e",
  "Silver Age (self-compiled compilation of Apple vs. 7G deluxe tracks)***e",
  "2012-2017 - Against All Logic***e",
  "Illusions of Shameless Abundance***e",
  "2017-2019***e",
  "Agent bla - Agent bla***r",
  "People Who Can Eat People Are The Luckiest People In The World - AJJ***r",
  "Momentary Masters - Albert Hammond, Jr.***r",
  "House of Sugar - Alex G***r",
  "Beach Music***r",
  "DSU***r",
  "Rocket***r",
  "Trick***r",
  "RULES***r",
  "Algiers - Algiers***r",
  "The Underside of Power***r",
  "There Is No Year***r",
  "Goddamnit! - Alkaline Trio***r",
  "Kids In the Street - The All-American Rejects***r",
  "Alvvays - Alvvays***r",
  "Antisocialites***r",
  "American Football - American Football***r",
  "Another Life - Amnesia Scanner***e",
  "Faith In Strangers - Andy Stott***e",
  "Luxury Problems***e",
  "It Should Be Us***e",
  "Never The Right Time***e",
  "Too Many Voices***e",
  "MY WOMAN - Angel Olsen***r",
  "All Mirrors***r",
  "Merriweather Post Pavilion - Animal Collective***p",
  "Strawberry Jam***p",
  "Sung Tongs***r",
  "Feels***r",
  "Spirit They’re Gone, Spirit They’ve Vanished***r",
  "Fall Be Kind***p",
  "Centipede Hz***r",
  "Painting With***p",
  "Water Curses***r",
  "People***r",
  "Here Comes The Indian***r",
  "Tangerine Reef***",
  "Meeting of the Waters***",
  "HOPELESSNESS - ANOHNI***p",
  "Paradise***p",
  "Hospice - The Antlers***r",
  "In The Attic Of The Universe***r",
  "I Am A Bird Now - Antony and the Johnsons***r",
  "Syro - Aphex Twin***e",
  "Selected Ambient Works 85-92***e",
  "Drukqs***e",
  "Collapse***e",
  "As Days Get Dark - Arab Strap***r",
  "Stretch 2 - Arca***e",
  "Mutant***e",
  "A New Place 2 Drown - Archy Marshall***e",
  "Funeral - Arcade Fire***r",
  "The Suburbs (Deluxe)***r",
  "Neon Bible***r",
  "Reflektor (Deluxe)***r",
  "Everything Now***r",
  "Whatever People Say I Am, That’s What I’m Not - Arctic Monkeys***r",
  "Favourite Worst Nightmare***r",
  "AM***r",
  "Tranquility Base Hotel & Casino***r",
  "thank u, next - Ariana Grande***p",
  "Positions***p",
  "Sweetener***p",
  "pom pom - Ariel Pink***p",
  "Dedicated To Bobby Jameson***p",
  "Before Today***p",
  "ULTRAPOP - The Armed***r",
  "Floor Seats - A$AP Ferg***h",
  "At. Long. Last. ASAP. - A$AP Rocky***h",
  "Live. Love. ASAP***h",
  "TESTING***h",
  "LONG.LIVE.A$AP (Deluxe)***h",
  "Thawing Dawn - A. Savage***r",
  "Hi, It’s Me - Ashnikko***h",
  "Logos - Atlas Sound***r",
  "Since I Left You - The Avalanches***e",
  "Down There - Avey Tare***r",
  "Cows on Hourglass Pond***r",
  "Enter the Slasher House - Avey Tare’s Slasher Flicks***r",
  "Broke With Expensive Taste - Azealia Banks",
  "The Melodic Blue - Baby Keem",
  "Doomin’ Sun - Bachelor***r",
  "III - Badbadnotgood***e",
  "Bad Brains - Bad Brains***r",
  "YHLQMDLG - Bad Bunny***p",
  "Puddinghead - Ball Park Music***r",
  "DRTY BWTY - Bames***e",
  "Stray - Bambara***r",
  "Shadow On Everything***r",
  "Utility - Barker***e",
  "Debiasing***e",
  "Obsidian - Baths***e",
  "Cerulean***e",
  "La Di Da Di - Battles***r",
  "Gloss Drop***r",
  "In The Flat Field (deluxe) - Bauhaus***r",
  "Beach Fossils - Beach Fossils***r",
  "Teen Dream - Beach House***p",
  "Bloom***p",
  "Depression Cherry***p",
  "Thank Your Lucky Stars***p",
  "The Things We Do To Find People Who Feel Like Us - Beach Slang***r",
  "A Loud Bash of Teenage Feelings***r",
  "Beat Happening - Beat Happening***r",
  "Sgt. Pepper’s Lonely Hearts Club Band - The Beatles***r",
  "Revolver***r",
  "Rubber Soul***r",
  "If You’re Feeling Sinister - Belle and Sebastian***r",
  "Dear Catastrophe Waitress***r",
  "The Boy With The Arab Strap***r",
  "Tigermilk***r",
  "How To Solve Our Human Problems***r",
  "Fold Your Hands Child, You Walk Like A Peasant***r",
  "The Plugs I Met - Benny The Butcher",
  "The Three EP’s - The Beta Band***r",
  "Beyoncé - Beyoncé***p",
  "Big Red Machine - Big Red Machine***e",
  "Capacity - Big Thief***r",
  "U.F.O.F.***r",
  "Two Hands***r",
  "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? - Billie Eilish***p",
  "Happier Than Ever***p",
  "Homogenic - Bjork***e",
  "For the first time - Black Country, New Road***r",
  "Ants From Up There***r",
  "Peaceful As Hell - Black Dresses***e",
  "My War - Black Flag***r",
  "Bigger Than Life - Black Marble***r",
  "It’s Immaterial***r",
  "schlagenheim - black midi***r",
  "Cavalcade***r",
  "Half Light - black taffy***e",
  "Opal Wand***e",
  "Red Light - Bladee",
  "Exeter",
  "333",
  "Eversince",
  "ICEDANCER",
  "Gluee",
  "Working on Dying",
  "EAT THE NIGHT (self-made compilation)",
  "The Fool",
  "Drain Your Life (self-made compilation)",
  "Good Luck - Bladee / Mechatok",
  "AvP - Bladee / Thaiboy Digital",
  "Gaia - Blank Banshee***e",
  "Silent Alarm - Bloc Party***r",
  "The Magic Whip - Blur***r",
  "Parklife***r",
  "Think Tank***r",
  "Music Has The Right To Children - Boards of Canada***e",
  "FIRE - B.o.B.",
  "Highway 61 Revisited - Bob Dylan***r",
  "Blonde On Blonde***r",
  "Rough and Rowdy Ways***r",
  "Blood On The Tracks***r",
  "Vacation - Bomb The Music Industry!***r",
  "Scrambles***r",
  "For Emma, Forever Ago - Bon Iver***r",
  "22, A Million***e",
  "USELESS - Bones",
  "Rotten",
  "Skinny",
  "AQUARIA - BOOTS***e",
  "The Devil and God Are Raging Inside Me - Brand New***r",
  "SATURATION II - BROCKHAMPTON",
  "iridescence",
  "GINGER",
  "You Forgot It In People - Broken Social Scene***r",
  "Nebraska - Bruce Springsteen***r",
  "Angels & Devils - The Bug***e",
  "London Zoo***e",
  "Fire***e",
  "Perfect From Now On - Built To Spill***r",
  "Keep It Like A Secret***r",
  "There Is No Enemy***r",
  "You In Reverse***r",
  "We Had A Good Time - Bullion***e",
  "pop songs 2020 - Bumper***p",
  "Burial - Burial***e",
  "Untrue***e",
  "Street Halo***e",
  "Kindred EP***e",
  "Rival Dealer***e",
  "Truant***e",
  "Ghost Hardware***e",
  "Young Death / Nightmarket***e",
  "Subtemple / Beachfires***e",
  "Rodent***e",
  "Claustro / State Forest***e",
  "Tunes 2011-2019***e",
  "Antidawn***e",
  "Thank You Happy Birthday - Cage the Elephant***r",
  "Social Cues***r",
  "Muvaland - Cakes da Killa / Proper Villains",
  "Tago Mago - Can***r",
  "Hidden Lands - Candy Claws***e",
  "Suddenly - Caribou***e",
  "Teens of Style - Car Seat Headrest***r",
  "Teens of Denial***r",
  "Nervous Young Man***r",
  "Twin Fantasy (Face to Face)***r",
  "Twin Fantasy (Mirror to Mirror)***r",
  "How To Leave Town***r",
  "Commit Yourself Completely***r",
  "Making a Door Less Open***r",
  "Emotion - Carly Rae Jepsen***p",
  "Pang - Caroline Polachek***p",
  "Radiance & Submission - CFCF***e",
  "memoryland***e",
  "Punk - CHAI***r",
  "WINK***r",
  "Moth - Chairlift***p",
  "Something***p",
  "Channel Tres - Channel Tres",
  "Black Moses",
  "I Can’t Go Outside",
  "Coloring Book - Chance the Rapper",
  "Pop 2 - Charli XCX***p",
  "Charli***p",
  "Sucker***p",
  "Number 1 Angel***p",
  "Vroom Vroom***p",
  "XCX World (fan compilation)***p",
  "how i’m feeling now***p",
  "Emphatically No. - Cheekface***r",
  "Thot Breaker - Chief Keef",
  "Finally Rich (Deluxe)",
  "4NEM",
  "GloToven",
  '“Awaken, My Love!” - Childish Gambino',
  "Hello People - Chris Reimer",
  "Malenkost - Cindy Lee***r",
  "What’s Tonight To Eternity***r",
  "Instrumentals - Clams Casino***e",
  "Instrumental Mixtape 2***e",
  "32 Levels***e",
  "Moon Trip Radio***e",
  "Instrumental Relics***e",
  "No Now - Clarence Clarity***e",
  "Clark - Clark***e",
  "London Calling - The Clash***r",
  "The Clash***r",
  "CLPPNG - clipping",
  "Splendor & Misery",
  "Hell Hath No Fury - Clipse",
  "Attack On Memory - Cloud Nothings***r",
  "Here and Nowhere Else***r",
  "Last Building Burning***r",
  "Grosses Wasser - Cluster***e",
  "POSH - Coco & Clair Clair***p",
  "Love Comes Close (Deluxe) - Cold Cave***e",
  "Cherish the Light Years***e",
  "Cremations***e",
  "Full Cold Moon***e",
  "Fate In Seven Lessons***e",
  "The Last Bookstore - Cole Withers***r",
  "Covert Contracts - Control Top***r",
  "Breathless (EP) - The Corrs***p",
  "Sometimes I Sit and Think, and Sometimes I Just Sit - Courtney Barnett***r",
  "The Double EP: A Sea of Split Peas***r",
  "Tell Me How You Really Feel***r",
  "Things Take Time, Take Time***r",
  "Lotta Sea Lice - Courtney Barnett / Kurt Vile***r",
  "We All Want The Same Things - Craig Finn***r",
  "Beyond The Feeling Gales - Crying***r",
  "Crystal Castles - Crystal Castles***e",
  "(II)***e",
  "(III)***e",
  "Amnesty (I)***e",
  "Asymmetry - Cuffed Up***r",
  "Disintegration - The Cure***r",
  "Pornography***r",
  "Covert Coup - Curren$y & The Alchemist",
  "Discovery - Daft Punk***e",
  "Homework***e",
  "Everyday Robots - Damon Albarn***e",
  "The Nearer the Fountain, More Pure the Stream Flows***e",
  "XXX (Deluxe) - Danny Brown",
  "Atrocity Exhibition",
  "Old",
  "uknowhatimsayin¿",
  "Harlecore - Danny L Harle***e",
  "1UL***e",
  "Broken Flowers***e",
  "Psychic - Darkside***e",
  "Unnatural Objects and Their Humans - David Boring***r",
  "Blackstar - David Bowie***r",
  "Hunky Dory***r",
  "Harmony House - Dayglow***r",
  "Dead Man’s Bones - Dead Man’s Bones***r",
  "Sunbather - Deafheaven***r",
  "Sleep Cycle - Deakin***r",
  "BLACK METAL 2 - Dean Blunt***e",
  "Transatlanticism - Death Cab for Cutie***r",
  "The Money Store - Death Grips",
  "Government Plates",
  "No Love Deep Web",
  "The Powers That B",
  "Exmilitary",
  "Bottomless Pit",
  "Fashion Week***e",
  "Year of the Snitch",
  "House On Wheels - Deb Never***p",
  "Halcyon Digest - Deerhunter***r",
  "Cryptograms***r",
  "Microcastle***r",
  "Weird Era Cont.***r",
  "Monomania***r",
  "Fading Frontier***r",
  "Why Hasn’t Everything Already Disappeared?***r",
  "TA13OO - Denzel Curry",
  "Imperial",
  "ZUU",
  "Payola - Desaparecidos***r",
  "Destroyer's Rubies - Destroyer***r",
  "Poison Season***r",
  "Q: Are We Not Men? A: We Are Devo! - Devo***r",
  "Is The Is Are - DIIV***r",
  "Badlands - Dirty Beaches***r",
  "Bitte Orca - Dirty Projectors***r",
  "Emergency & I - The Dismemberment Plan***r",
  "Collector - Disq***r",
  "No Sleep - DJ Esco",
  "Project E.T.",
  "KOLORBLIND",
  "Knock Knock - DJ Koze***e",
  "Take Off Mode - DJ Nate***e",
  "Da Trak Genious***e",
  "Double Cup - DJ Rashad***e",
  "Mirrors - DJ Seinfeld***e",
  "Time Spent Away From U***e",
  "frailty - dltzk***p",
  "Drabbad av sjukdom - Dod Mark***r",
  "Demons R Us - Doe Boy & Southside",
  "Melee - Dogleg***r",
  "Nectar Fields - Dolores***r",
  "Flamboyant (Deluxe) - Dorian Electra***p",
  "4 New Hit Songs - Doss***e",
  "Cost of Living - Downtown Boys***r",
  "Trash Island - Drain Gang",
  "D&G",
  "Surf - Donnie Trumpet & The Social Experiment",
  "If You’re Reading This It’s Too Late - Drake",
  "Scorpion",
  "Dark Lane Demo Tapes",
  "Certified Lover Boy",
  "What a Time to Be Alive - Drake / Future",
  "Thank You For Using GTL - Drakeo the Ruler & JoogSzn",
  "Future Nostalgia - Dua Lipa***p",
  "Club Nites - Dumb***r",
  "Mediation of Ecstatic Energy - Dustin Wong***r",
  "Doris - Earl Sweatshirt",
  "EARL",
  "I Don’t Like Shit, I Don’t Go Outside",
  "Brighter Days",
  "Some Rap Songs",
  "FEET OF CLAY (Deluxe)",
  "Sick!",
  "E - ECCO2K***e",
  "Pxe***e",
  "Crying Over Pros for No Reason - edIT***e",
  "Certified Air Raid Material***e",
  "Up From Below - Edward Sharpe and the Magnetic Zeros***r",
  "Sensational - Erika de Casier***p",
  "Quivering In Time - Eris Drew***e",
  "Get To Heaven - Everything Everything***r",
  "Re-Animator***r",
  "Rips - Ex Hex***r",
  "Exocomet - Exocomet***r",
  "This Nation’s Saving Grace - The Fall***r",
  "Hex Enduction Hour***r",
  "Songs For Our Mothers - The Fat White Family***r",
  "Serfs Up!***r",
  "Champagne Holocaust***r",
  "I’m A Piece of Shit - Father",
  "Who’s Gonna Get Fucked First",
  "Young Hot Ebony",
  "L1L D1DDY",
  "Papicodone EP",
  "Awful Swim",
  "Hu$band",
  "Tha Thingz I Do Money",
  "I Love You, Honeybear - Father John Misty***r",
  "Fear Fun***r",
  "Pure Comedy***r",
  "God’s Favorite Customer***r",
  "FxG3000 - Fax Gang***e",
  "Funky Was The State of Affairs - Fergus & Geronimo***r",
  "Fever Ray - Fever Ray***e",
  "Plunge***e",
  "Field Whispers (Into The Crystal Palace) - FIRE-TOOLZ***e",
  "For Collectors Only - The Five Satins***p",
  "EP2 - FKA twigs***e",
  "LP1***e",
  "M3LL155X***e",
  "MAGDALENE***e",
  "CAPRISONGS***e",
  "Helplessness Blues - Fleet Foxes***r",
  "Crack-Up***r",
  "Elaenia - Floating Points***e",
  "Crush***e",
  "Hi This Is Flume - Flume***e",
  "Los Angeles - Flying Lotus***e",
  "Until the Quiet Comes***e",
  "Cosmogramma***e",
  "Pattern+Grid World***e",
  "You’re Dead!***e",
  "Flamagra***e",
  "Holy Fire - Foals***r",
  "What Went Down***r",
  "Everything Not Saved Will Be Lost Part 1***r",
  "Dogrel - FONTAINES D.C.***r",
  "A Hero’s Death***r",
  "Channel Pressure - Ford & Lopatin***e",
  "Torches - Foster the People***r",
  "Rounds - Four Tet***e",
  "There Is Love In You***e",
  "channel ORANGE - Frank Ocean",
  "blonde",
  "Nostalgia, Ultra",
  "Next Thing - Frankie Cosmos***r",
  "Zentropy***r",
  "Franz Ferdinand - Franz Ferdinand***r",
  "Always Ascending***r",
  "You Could Have It So Much Better***r",
  "Tonight: Franz Ferdinand***r",
  "Feeling Cool and Normal - fraxiom***e",
  "Talon of the Hawk - The Front Bottoms***r",
  "Dose Your Dreams - Fucked Up***r",
  "Some Nights - fun.***r",
  "DS2 - Future",
  "56 Nights",
  "Beast Mode",
  "Monster",
  "Purple Reign",
  "EVOL",
  "Honest (Deluxe)",
  "FUTURE",
  "HDNRXX",
  "BEASTMODE 2",
  "The WIZRD",
  "2019 [fan compilation]",
  "SAVE ME",
  "Streetz Callin",
  "Pluto 3D",
  "High Off Life",
  "Astronaut Status",
  "FBG: The Movie",
  "Pluto x Baby Pluto (Deluxe) - Future / Lil Uzi Vert",
  "SUPER SLIMEY - Future / Young Thug",
  "Singles - Future Islands***r",
  "In The Evening Air***r",
  "Wave Like Home***r",
  "The Far Field***r",
  "Entertainment! - Gang Of Four***r",
  "Narkopop - GAS***e",
  "Animal Shapes - Geographer***p",
  "SLIDE - George Clanton***e",
  "Virtual Vacation - George Ergemlidze***e",
  "Needs - Giraffage***e",
  "All Dogs Go To Heaven - Glaive***p",
  "JUST SAY NO TO THE PSYCHO RIGHT-WING CAPITALIST FASCIST INDUSTRIAL DEATH MACHINE - Gnod***r",
  "Goat Girl - Goat Girl***r",
  "Lift Your Skinny Fists Like Antennas to Heaven - Godspeed You! Black Emperor***r",
  "Cruel Summer - GOOD Music",
  "Demon Days - Gorillaz***e",
  "Sumday - Grandaddy***r",
  "The Sophtware Slump (Deluxe)***r",
  "Just Like the Fambly Cat***r",
  "Last Place***r",
  "Under the Western Freeway***r",
  "Concrete Dunes***r",
  "A Pretty Mess By This One Band***r",
  "Signal to Snow Ratio***r",
  "Excerpts from the Diary of Todd Zilla***r",
  "American Beauty - Grateful Dead***r",
  "Workingman’s Dead***r",
  "American Idiot - Green Day***r",
  "Visions - Grimes***e",
  "Geidi Primes***e",
  "Art Angels***p",
  "Halfaxa***e",
  "Miss Anthropocene***p",
  "Beautiful, Wonderful - Gud***e",
  "Bee Thousand - Guided By Voices***r",
  "WUNNA - Gunna",
  "Drip Harder - Gunna / Lil Baby",
  "None - gupi",
  "Audio Drag for Ego Slobs - Gustaf***r",
  "BADLANDS - Halsey***p",
  "If I Can’t Have Love, I Want Power***p",
  "The Loves of Your Life - Hamilton Leithauser***r",
  "I Had A Dream That You Were Mine - Hamilton Leithauser + Rostam***r",
  "Reflections - Hannah Diamond***p",
  "Reflections Remixes***p",
  "I’m Sure - Harmless***r",
  "Death Magic - Health***r",
  "GET COLOR***r",
  "Dreamboat Annie - Heart***r",
  "The Hecks - The Hecks***r",
  "Tawk Tomahawk - Hiatus Kaiyote***e",
  "Boys and Girls in America - The Hold Steady***r",
  "I Became Birds - Home Is Where***r",
  "V - The Horrors***e",
  "Heavy Lifter - Hovvdy***r",
  '“What Is This Heart?” - How To Dress Well***e',
  "Hyd - Hyd***p",
  "Plowing Into the Field of Love - Iceage***r",
  "Beyondless***r",
  "You’re Nothing***r",
  "New Brigade***r",
  "Seek Shelter***r",
  "Brutalism - Idles***r",
  "Welcome***r",
  "Joy As An Act of Resistance***r",
  "Ultra Mono***r",
  "Crawler***r",
  "Chinese Nü Year EP - Iglooghost***e",
  "I Love Makonnen - ILoveMakonnen",
  "I LOVE MAKONNEN 2",
  "Any Shape You Take - Indigo De Souza***r",
  "By The Time I Get To Phoenix - Injury Reserve",
  "Turn On the Bright Lights - Interpol***r",
  "El Pintor***r",
  "Antics***r",
  "Interpol***r",
  "El Pintor Bonus Tracks***r",
  "Marauder***r",
  "Out of Touch - Jaakko Eino Kalevi***r",
  "Dissolution***r",
  "Hard Hold - Jaala***r",
  "Leak 04-13 (Bait Ones) - Jai Paul***p",
  "James Blake - James Blake***e",
  "Klavierwerke***e",
  "The Colour In Anything***e",
  "200 Press EP***e",
  "Assume Form***e",
  "Before***e",
  "Friends That Break Your Heart***e",
  "The Inheritors - James Holden***e",
  "3 - Jamie Isaac / Nosaj Thing***e",
  "In Colour - Jamie xx***e",
  "Celebration Rock - Japandroids***r",
  "Post-Nothing***r",
  "Psychopomp - Japanese Breakfast***r",
  "Where Is My Great Big Feeling?***r",
  "Soft Sounds From Another Planet***r",
  "Jubilee***r",
  "Japanese Wallpaper - Japanese Wallpaper***e",
  "Yours Truly, The Commuter - Jason Lytle***r",
  "Dept. of Disappearance (Deluxe)***r",
  "NYLONANDJUNO***r",
  "Everybody Works - Jay Som***r",
  "2014 Forest Hills Drive - J Cole",
  "We Cool? - Jeff Rosenstock***r",
  "WORRY.***r",
  "POST-***r",
  "I Look Like Shit***r",
  "NO DREAM***r",
  "2020 DUMP***r",
  "Blood Bitch - Jenny Hval***e",
  "Late Nights: The Album - Jeremih",
  "What’s Your Pleasure? - Jessie Ware***p",
  "Oh No - Jessy Lanza***e",
  "Pull My Hair Back***e",
  "All The Time***e",
  "24/7***e",
  "DJ-Kicks: Jessy Lanza (Exclusives)***e",
  "Psychocandy - The Jesus and Mary Chain***r",
  "Dark Energy - JLin***e",
  "Galaxy Crisis: The Strangest Midnight Broadcast - Joanna Wang***p",
  "Wicked City - Jockstrap***p",
  "Summer Knights - Joey Bada$$",
  "Singularity - Jon Hopkins***e",
  "Unknown Pleasures - Joy Division***r",
  "Closer***r",
  "Still [Collector’s Edition]***r",
  "Veteran - JPEGMAFIA",
  "Black Ben Carson",
  "All My Heroes Are Cornballs",
  "LP!",
  "Have You In My Wilderness - Julia Holter***r",
  "Phrazes For The Young - Julian Casablancas***r",
  "Big Black Coat - Junior Boys***e",
  "The 20/20 Experience (Deluxe) - Justin Timberlake***p",
  "Golden Hour - Kacey Musgraves***r",
  "Por Vida - Kali Uchis***p",
  "My Beautiful Dark Twisted Fantasy - Kanye West",
  "808s & Heartbreak",
  "Yeezus",
  "The Life of Pablo",
  "The College Dropout",
  "Ye",
  "Jesus Is King",
  "Yandhi",
  "Donda",
  "Hounds of Love - Kate Bush***r",
  "99.9% - Kaytranada***e",
  "Take Me Apart - Kelela",
  "good kid, m.A.A.d. city - Kendrick Lamar",
  "To Pimp A Butterfly",
  "untitled unmastered.",
  "DAMN.",
  "Black Panther: The Album",
  "Bonito Generation - Kero Kero Bonito***e",
  "Time ‘n’ Place***p",
  "TOTEP***p",
  "Intro Bonito***e",
  "Civilisation I***e",
  "MTV1987 - Kevin Abstract",
  "Islah - Kevin Gates",
  "Stranger Than Fiction",
  "I’m Him",
  "Oh My God - Kevin Morby***r",
  "Singing Saw***r",
  "City Music***r",
  "Still Life***r",
  "Sundowner***r",
  "KIDS SEE GHOSTS - KIDS SEE GHOSTS",
  "REDUX - Kilo Kish***p",
  "In the Court of the Crimson King - King Crimson***r",
  "King Krule - King Krule***r",
  "6 Feet Beneath the Moon***r",
  "The OOZ***r",
  "Man Alive!***r",
  "Riot On An Empty Street - Kings of Convenience***r",
  "Silent Shout - The Knife***e",
  "Shaking The Habitual***e",
  "Deep Cuts***e",
  "Kontravoid - Kontravoid***e",
  "Agor - Koreless***e",
  "Grievances - Kowloon Walled City***r",
  "Computer World - Kraftwerk***e",
  "b’lieve i’m goin’ down… - Kurt Vile***r",
  "Wakin On A Pretty Daze: Deluxe Daze (Post Haze)***r",
  "So Outta Reach***r",
  "Smoke Ring for My Halo***r",
  "In My Time***r",
  "Constant Hitmaker***r",
  "Bottle It In***r",
  "Speed, Sound, Lonely KV***r",
  "Parallelogram - Kurt Vile / Steve Gunn***r",
  "Norman Fucking Rockwell! - Lana Del Rey***p",
  "I Need New Eyes - Larry Gus***e",
  "Quarantine - Laurel Halo***e",
  "Sound of Silver - LCD Soundsystem***e",
  "American Dream***e",
  "This Is Happening***e",
  "Electric Lady Sessions***e",
  "Kuang EP - Lee Gamble***e",
  "Nothing Is Still - Leon Vynehall***e",
  "Rojus (Designed To Dance)***e",
  "Music for the Uninvited***e",
  "Rare, Forever***e",
  "I’m All Ears - Let’s Eat Grandma***p",
  "HELLBOY - Lil Peep",
  "Oblivion Access - LIL UGLY MANE",
  "Mista Thug Isolation",
  "Lil Uzi Vert vs. The World - Lil Uzi Vert",
  "Luv Is Rage 2",
  "Eternal Atake (Deluxe)",
  "Lil Boat - Lil Yachty",
  "Lily We Need to Talk Now - Lily Konigsberg***r",
  "GREY Area - Little Simz",
  "Mama Said Knock You Out - LL Cool J",
  "Melodrama - Lorde***p",
  "Pure Heroine (Extended)***p",
  "Solar Power***p",
  "Te Ao Marama***p",
  "Agitations - Lotic***e",
  "Heterocetera***e",
  "Spooky Action At A Distance - Lotus Plaza***r",
  "The Blue Mask - Lou Reed***r",
  "Transformer***r",
  "New York***r",
  "Berlin***r",
  "Lou Reed***r",
  "Ecstasy***r",
  "New Sensations***r",
  "Mistrial***r",
  "Set the Twilight Reeling***r",
  "Coney Island Baby***r",
  "Growing Up In Public***r",
  "Legendary Hearts***r",
  "Rock and Roll Heart***r",
  "Double Negative - Low***r",
  "Freewave 3 - Lucki",
  "Days B4 III",
  "Almost There",
  "Watch My Back",
  "Alternative Trap",
  "Days B4 II",
  "Freewave 2",
  "WAKE UP LUCKI - Lucki & F1LTHY",
  "Bizarster - Luke Vibert***e",
  "Hurry Up, We’re Dreaming - M83***e",
  "Dead Cities, Red Seas & Lost Ghosts***e",
  "Salad Days - Mac Demarco***r",
  "This Old Dog***r",
  "Here Comes The Cowboy***r",
  "GO:OD AM - Mac Miller",
  "Bad Neighbor - Madlib / MED / Blu",
  "Real Life - Magazine***r",
  "No Thyself***r",
  "The Correct Use of Soap (Deluxe)***r",
  "Secondhand Daylight***r",
  "A Little Rhythm and a Wicked Feeling - Magdalena Bay***p",
  "Mini Mix, Vol. 2***p",
  "Mini Mix, Vol. 1***p",
  "Mercurial World***p",
  "Impersonator - Majical Cloudz***e",
  "For Allting - Makthaverskan***r",
  "Telling It Like It Is - Marching Church***r",
  "FROOT - MARINA***p",
  "Ancient Dreams in a Modern Land***p",
  "Whole Lotta Red - Mario Judah",
  "Mezzanine - Massive Attack***e",
  "Ritual Spirit***e",
  "Starsick - Maude Latour***p",
  "#MAXO187 - Maxo Kream",
  "Brandon Banks",
  "Money Worth More Than Dreams - Meek Mill",
  "Impazamo - Menzi***e",
  "Moloch - Merkabah***r",
  "NOT ALL HEROES WEAR CAPES - Metro Boomin",
  "II - Metz***r",
  "Oracular Spectacular - MGMT***r",
  "Congratulations***r",
  "Little Dark Age***r",
  "Kala (Deluxe) - M.I.A.***p",
  "The Water[s] - Mick Jenkins",
  "Crumbling - Mid-Air Thief***r",
  "CULTURE - Migos",
  "Culture II",
  "Faint Hearted - Miles Whittaker***e",
  "So the Flies Don't Come - Milo",
  "Who Told You To Think??!!?!?!?!",
  "Puberty 2 - Mitski***r",
  "Bury Me at Makeout Creek***r",
  "Be The Cowboy***r",
  "Retired From Sad, New Career In Business***r",
  "Laurel Hell***p",
  "Holy Ghost - Modern Baseball***r",
  "The Modern Lovers - The Modern Lovers***r",
  "The Moon & Antarctica - Modest Mouse***r",
  "The Lonesome Crowded West***r",
  "Good News For People Who Love Bad News***r",
  "Night On The Sun***r",
  "Everywhere and His Nasty Parlour Tricks***r",
  "This Is A Long Drive For Someone With Nothing To Think About***r",
  "Strangers to Ourselves",
  "SINNER - Moodymann***e",
  "Bath Songs - The Moondrops***r",
  "Proto - Mumdance & Logos***e",
  "Loveless - My Bloody Valentine***r",
  "Unlimited Ammo - Namasenda***p",
  "February 15 - NAO",
  "Boxer - The National***r",
  "High Violet***r",
  "Trouble Will Find Me***r",
  "Sleep Well Beast***r",
  "NAV - NAV",
  "Psychic Chasms - Neon Indian***e",
  "Era Extraña***e",
  "Vega Intl. Night School***e",
  "In the Aeroplane Over the Sea - Neutral Milk Hotel***r",
  "Music Complete - New Order***r",
  "Technique***r",
  "Brotherhood (Collector’s Edition)***r",
  "Live at Bestival 2012***r",
  "Lost Sirens***r",
  "Power, Corruption, & Lies***r",
  "Republic***r",
  "Movement***r",
  "New York Dolls - New York Dolls***r",
  "In Too Much Too Soon***r",
  "Skeleton Tree - Nick Cave & The Bad Seeds***r",
  "Let Love In***r",
  "Space Is Only Noise - Nicolas Jaar***e",
  "Sirens (Deluxe)***e",
  "Nymphs***e",
  "Pomegranates***e",
  "Cenizas***e",
  "Danger - Nidia Minaj***e",
  "Drift - Nosaj Thing***e",
  "Home***e",
  "Fated***e",
  "No Reality***e",
  "Parallels***e",
  "Miss Universe - Nilüfer Yanya***r",
  "The Downward Spiral - Nine Inch Nails***r",
  "Dream Sequins - Nmesh***e",
  "SUPERBEANMAN - nolanberollin",
  "Flatland - Objekt***e",
  "Things I Never Said - Oceanator***r",
  "Resonant Body - Octo Octa***e",
  "The OF Tape Vol 2. - Odd Future",
  "FATHER OF - Offset",
  "Multi-Task - Omni***r",
  "R Plus Seven - Oneohtrix Point Never***e",
  "Replica***e",
  "Returnal***e",
  "The Fall Into Time***e",
  "Drawn and Quartered***e",
  "Garden of Delete***e",
  "Zones Without People***e",
  "Age Of***e",
  "Love In The Time of Lexapro***e",
  "The Station***e",
  "Rifts***e",
  "KCRW Session***e",
  "Uncut Gems***e",
  "Magic Oneohtrix Point Never (Deluxe)***e",
  "Faminine Mystique - oOoOO / Islamiq Girls***e",
  "Architecture & Morality (Deluxe) - Orchestral Manoeuvres In The Dark***e",
  "Hunger In Me Living - Organ Tapes***e",
  "HTTP404 - Oscar Scheller***p",
  "Boys Cry***p",
  "Devil’s Dance - Ossia***e",
  "Sun Coming Down - Ought***r",
  "More Than Any Other Day***r",
  "Once More With Feeling EP***r",
  "Room Inside The World***r",
  "Angles & Planes - Paintwork***r",
  "Dry Food - Palehound***r",
  "Bent Nail EP***r",
  "A Place I’ll Always Go***r",
  "Black Friday***r",
  "Trading Basics - Palm***r",
  "Person Pitch - Panda Bear***p",
  "Panda Bear Meets the Grim Reaper***p",
  "If U Want It - Park Hye Jin***e",
  "Content Nausea - Parquet Courts***r",
  "Tally All The Things That You Broke***r",
  "Sunbathing Animal***r",
  "Monastic Living***r",
  "Human Performance***r",
  "Light Up Gold***r",
  "Wide Awake!***r",
  "Play On Parquet Courts***r",
  "Sympathy For Life***r",
  "MILANO - Parquet Courts / Danielle Luppi / Karen O***r",
  "Horses - Patti Smith***r",
  "Crooked Rain, Crooked Rain - Pavement***r",
  "Wowee Zowee***r",
  "Slanted & Enchanted***r",
  "Terror Twilight***r",
  "Sugar - PAWWS***p",
  "PC Music, Vol. 1 - PC Music***p",
  "PC Music, Vol. 2***p",
  "Once - Peggy Gou***e",
  "No Shape - Perfume Genius***r",
  "Set My Heart On Fire Immediately***r",
  "Wolfgang Amadeus Phoenix - Phoenix***r",
  "The Life of Pi’erre 5 - Pi’erre Bourne",
  "The Life of Pi’erre 4 (Deluxe)",
  "Yo!88 - Pi’erre Bourne & TM88",
  "A Hairshirt of Purpose - Pile***r",
  "Cardinal - Pinegrove***r",
  "Everything So Far***r",
  "Audiotree Live***r",
  "The Dark Side of the Moon - Pink Floyd***r",
  "Surfer Rosa - Pixies***r",
  "Doolittle***r",
  "Bossanova***r",
  "Head Carrier***r",
  "to hell with it - PinkPantheress***p",
  "The Age of Anxiety - Pixx***p",
  "Devotion - Planet 1999***e",
  "Playboi Carti - Playboi Carti",
  "Die Lit",
  "Whole Lotta Leaks",
  "PLAYBOI MAG",
  "ok!*^+:)",
  "Whole Lotta Red",
  "OPIUM (compilation)",
  "CARTI_XCX - Playboi Carti / Charli XCX (mashup)",
  "Ploegendienst - Ploegendienst***r",
  "Die A Legend - Polo G",
  "Man It Feels Like Space Again - Pond***r",
  "The Weather***r",
  "Tasmania***r",
  "Beards, Wives, Denim***r",
  "9***r",
  "Meet the Woo - Pop Smoke",
  "I Disagree - Poppy***r",
  "Every Bad - Porridge Radio***r",
  "Dummy - Portishead***r",
  "Third***r",
  "Viet Cong - Preoccupations***r",
  "Cassette***r",
  "Preoccupations***r",
  "New Material***r",
  "Bodies and Control and Money and Power - Priests***r",
  "Nothing Feels Natural***r",
  "The Seduction of Kansas***r",
  "The Agent Intellect - Protomartyr***r",
  "Under Color of Official Right***r",
  "No Passion All Technique***r",
  "Relatives In Descent***r",
  "Consolation EP***r",
  "Irony Prompts a Party Rat - Protomarty / Spray Paint***r",
  "Ultimate Success Today***r",
  "Body Jumper - provoker***r",
  "Frozen Niagara Falls - Prurient***x",
  "First Issue - Public Image Ltd.***r",
  "The Dream Is Over - PUP***r",
  "Morbid Stuff***r",
  "Shrines - Purity Ring***p",
  "My Name Is My Name - Pusha T",
  "Darkest Before Dawn",
  "DAYTONA",
  "Drive-By Lullabies - p4rkr***p",
  "Quality Control: Control the Streets Volume 1 - Quality Control",
  "The Bends - Radiohead***r",
  "Kid A***r",
  "OK Computer OKNOTOK 1997 2017***r",
  "Amnesiac***e",
  "A Moon Shaped Pool***r",
  "In Rainbows***r",
  "In Rainbows Disk 2***r",
  "Hail to the Thief***r",
  "SremmLife - Rae Sremmurd",
  "SremmLife 2",
  "SR3MM",
  "Arcadia - Ramona Lisa***p",
  "Ramones - The Ramones***r",
  "Classics - Ratatat",
  "Wiki93 - RATKING",
  "Murmur - R.E.M.***r",
  "Let It Be - The Replacements***r",
  "The Sailor - Rich Brian",
  "Rich Gang: Tha Tour Pt. 1 - Rich Gang",
  "Anger Management - Rico Nasty & Kenny Beats",
  "Peasant - Richard Dawson***r",
  "SAWAYAMA - Rina Sawayama***p",
  "RipSquad - RipSquad (self-compiled)***e",
  "Instrumentals 2015-2020 (Soulseek compilation)***e",
  "Ghetto Ass Witch - Ritualz***e",
  "Howl - Rival Consoles***e",
  "Odyssey / Sonne (Deluxe)***e",
  "Night Melody***e",
  "Persona***e",
  "OVERFLOW***e",
  "Honey - Robyn***p",
  "Every Picture Tells A Story - Rod Stewart***r",
  "Flowers From Exile - Rome***r",
  "Tread - Ross From Friends***e",
  "Half-Light - Rostam***p",
  "Roxy Music - Roxy Music***r",
  "Run the Jewels 2 - Run the Jewels",
  "Hometowns - The Rural Alberta Advantage***r",
  "The Wild***r",
  "Glass Swords - Rustie***e",
  "100 Miles & Walk’in - Rx Papi",
  "Foreign Exchange - Rx Papi & Gud",
  "Dreaming of David - Ryan Beatty***p",
  "5 - Sault***r",
  "Adore Life - Savages***r",
  "SBTRKT - SBTRKT***e",
  "Wonder Where We Land (Deluxe)***e",
  "Transitions***e",
  "That’s Harakiri - Sd Laika***e",
  "Romeo - Sega Bodega***e",
  "Mind Game - Seiichi Yamamoto***r",
  "soil - serpentwithfeet",
  "Songs of Praise - Shame***r",
  "Drunk Tank Pink***r",
  "Lineage - Shigeto***e",
  "I Know You Like It - Shinichiro Yokota***e",
  "Oh, Inverted World - The Shins***r",
  "Wincing the Night Away***r",
  "Port of Morrow***r",
  "Heartworms***r",
  "The Worm’s Heart***r",
  "Chutes Too Narrow***r",
  "Bad Vibes - Shlohmo***e",
  "Dark Red***e",
  "Dark Red Remixes***e",
  "Fine, Thanks***e",
  "Laid Out***e",
  "Rock Music***e",
  "The End***e",
  "Camping***e",
  "Bad Vibes: Rarities + Extras***e",
  "Heaven Inc.***e",
  "No More - Shlohmo / Jeremih",
  "ALIAS - Shygirl",
  "Agaetis byrjun - Sigur Ros***r",
  "American Water - Silver Jews***r",
  "yikes! - Silver Sphere***p",
  "Sisyphus - Sisyphus***e",
  "Compro - Skee Mask***e",
  "ISS004***e",
  "808BB***e",
  "ISS006***e",
  "Pool***e",
  "ISS005***e",
  "Konnichiwa - Skepta",
  "At the Moonbase - Slaughter Beach, Dog***r",
  "Dig Me Out - Sleater Kinney***r",
  "No Cities To Love***r",
  "The Woods***r",
  "Spiderland - Slint***r",
  "Digital Resistance - Slough Feg***r",
  "Nothing Great About Britain - slowthai",
  "Siamese Dream - The Smashing Pumpkins***r",
  "Monuments to an Elegy***r",
  "Mellon Collie and the Infinite Sadness***r",
  "Hatful Of Hollow - The Smiths***r",
  "The Queen Is Dead***r",
  "A Shapeless Pool of Lovely Pale Colours Suspended in the Darkness - Smurphy***e",
  "Lush - Snail Mail***r",
  "Valentine***r",
  "The Snakes - The Snakes***r",
  "Henry / I’m On Fire - Soccer Mommy***r",
  "A Seat At The Table - Solange",
  "When I Get Home",
  "Daydream Nation (Deluxe) - Sonic Youth***r",
  "Sister***r",
  "Dirty***r",
  "Washing Machine***r",
  "Deus Sex Machina: Or, Moving Slowly Beyond Nikola Tesla - Sons of an Illustrious Father***r",
  "Oil of Every Pearl’s Un-Insides - SOPHIE***e",
  "Hypnic Jerks - Spirit of the Beehive***r",
  "ENTERTAINMENT, DEATH***r",
  "Try To Be Hopeful - The Spook School***r",
  "Ga Ga Ga Ga Ga - Spoon***r",
  "Gimme Fiction***r",
  "Hot Thoughts***r",
  "Bright Green Field - Squid***r",
  "Is This It - The Strokes***r",
  "Room on Fire***r",
  "First Impressions of Earth***r",
  "Angles***r",
  "Comedown Machine***r",
  "Future Present Past***r",
  "The New Abnormal***r",
  "Actor - St. Vincent***r",
  "Strange Mercy***r",
  "St. Vincent***r",
  "MASSEDUCTION***r",
  "MassEducation***r",
  "Daddy’s Home***r",
  "Illinois - Sufjan Stevens***r",
  "Michigan***r",
  "Enjoy Your Rabbit***e",
  "The Age of Adz***e",
  "Carrie & Lowell***r",
  "The Avalanche***r",
  "The Ascension***r",
  "Benji - Sun Kil Moon***r",
  "Superorganism - Superorganism***e",
  "Close Your Eyes (And Feel) - Supreems***e",
  "SGV1 - Surf Gang",
  "Paprika (From the Motion Picture) - Susumu Hirasawa***e",
  "Horoscope - Suzanne Kraft***e",
  "Talk From Home***e",
  "What You Get for Being Young***e",
  "About You***e",
  "Filth - Swans***r",
  "velocity:design:comfort - Sweet Trip***e",
  "...In “Jane From Occupied Europe” - Swell Maps***r",
  "Remain In Light - Talking Heads***r",
  "Speaking In Tongues***r",
  "Talking Heads: 77***r",
  "The Wild Hunt - The Tallest Man on Earth***r",
  "InnerSpeaker - Tame Impala***r",
  "Lonerism***r",
  "Currents***r",
  "The Slow Rush***r",
  "High Pitched and Moist - Tami T***p",
  "Denton After Sunset - Teenage Cool Kids***r",
  "Foreign Lands***r",
  "Marquee Moon - Television***r",
  "Adventure***r",
  "Television***r",
  "Conditions - The Temper Trap***p",
  "Legendary Member - Thaiboy Digital",
  "Tiger",
  "Black Rose: A Rock Legend - Thin Lizzy***r",
  "Through the Green - Tiger & Woods***e",
  "spin - Tigers Jaw***r",
  "Saturday Night - Tim Darcy***r",
  "Virgins - Tim Hecker***e",
  "Timetable Vol. 2 - Timetable Records***e",
  "The Monitor - Titus Andronicus***r",
  "The Airing of Grievances***r",
  "Local Business***r",
  "The Most Lamentable Tragedy***r",
  "An Obelisk***r",
  "A Productive Cough***r",
  "Home Alone on Halloween***r",
  "It’s Album Time - Todd Terje***e",
  "Tom Verlaine - Tom Verlaine***r",
  "Dreamtime***r",
  "Flash Light***r",
  "Rain Dogs - Tom Waits***r",
  "Tommy Genesis - Tommy Genesis",
  "June 2009 - Toro y Moi***e",
  "Anything in Return***e",
  "What For?***e",
  "Samantha***e",
  "Outer Peace***e",
  "smartbeats***e",
  "Soul Trash***e",
  "Desiderium - Tokimonsta***e",
  "Laughing At The System - Total Control***r",
  "No Peace - Trash Talk***r",
  "Days Before Rodeo - Travis Scott",
  "Rodeo (Deluxe)",
  "Birds in the Trap Sing McKnight",
  "Travis La Flame",
  "ASTROWORLD",
  "Huncho Jack, Jack Huncho - Travis Scott / Quavo",
  "Mulberry Violence - Trevor Powers***e",
  "Triad - Triad God",
  "Return to Cookie Mountain (Deluxe) - TV On The Radio***r",
  "Dear Science (Deluxe)***r",
  "Goblin - Tyler, the Creator",
  "Cherry Bomb",
  "Bastard",
  "Flower Boy",
  "IGOR",
  "CALL ME IF YOU GET LOST",
  "東方不敗 - Tzusing***e",
  "Unknown Mortal Orchestra - Unknown Mortal Orchestra***r",
  "In A Poem Unlimited - U.S. Girls***p",
  "Half Free***p",
  "Heavy Light***p",
  "GEM***p",
  "Good Job, You Found Me- Valee",
  "VTM - Valee & ChaseTheMoney",
  "Gimme Five Im High",
  "Vampire Weekend - Vampire Weekend***r",
  "Contra***r",
  "Modern Vampires of the City***r",
  "Father of the Bride***r",
  "The Velvet Underground & Nico - The Velvet Underground***r",
  "Loaded***r",
  "White Light / White Heat***r",
  "The Velvet Underground***r",
  "Hell Can Wait - Vince Staples",
  "Summertime '06",
  "Shyne Coldchain Vol. 2",
  "Big Fish Theory",
  "Prima Donna",
  "FM!",
  "Vince Staples",
  "Violent Femmes - Violent Femmes***r",
  "Tyranny - The Voidz***r",
  "Virtue***r",
  "Flockaveli - Waka Flocka Flame",
  "Lost In The Dream - The War on Drugs***r",
  "Slave Ambient***r",
  "Wagonwheel Blues***r",
  "A Deeper Understanding***r",
  "I Don’t Live Here Anymore***r",
  "Fisherman’s Blues - The Waterboys***r",
  "V - Wavves***r",
  "King of the Beach***r",
  "Afraid of Heights***r",
  "You’re Welcome***r",
  "Wavves***r",
  "Emo Christmas***r",
  "Wavvves***r",
  "Hideaway***r",
  "No Life For Me - Wavves x Cloud Nothings***r",
  "Beauty Behind the Madness - The Weeknd",
  "After Hours (Deluxe)",
  "Starboy",
  "House of Balloons",
  "Echoes of Silence",
  "Dawn FM",
  "The Blue Album - Weezer***r",
  "Pinkerton***r",
  "The White Album***r",
  "OK Human***r",
  "Titanic Rising - Weyes Blood***p",
  "Front Row Seat To Earth***p",
  "@ My Whit’s End - WHARFWHIT***e",
  "Downer - Whitearmor***e",
  "Love Spectrum - Whoarei***e",
  "Policy - Will Butler***r",
  "Pink Flag - Wire***r",
  "152***r",
  "Chairs Missing***r",
  "Silver / Lead***r",
  "Blue Summer - Woesum",
  "Blue Weekend - Wolf Alice***r",
  "Cry Cry Cry - Wolf Parade***r",
  "Apologies to the Queen Mary***r",
  "Women - Women***r",
  "Public Strain***r",
  "First World Record - The World***r",
  "Annabel Dream Reader - The Wytches***r",
  "Knife Play - Xiu Xiu***r",
  "A Promise***r",
  "Fabulous Muscles***r",
  "Plays The Music Of Twin Peaks***r",
  "FORGET***r",
  "xx - The xx***e",
  "XXYYXX - XXYYXX***e",
  "EP2 - Yaeji***e",
  "WHAT WE DREW 우리가 그려왔던***e",
  "RIFT One - YEAR0001***e",
  "Up 2 Më - Yeat",
  "Serotonin II - yeule***e",
  "Coma***e",
  "Glitch Princess***e",
  "I Can Hear the Heart Beating As One - Yo La Tengo***r",
  "Painful***r",
  "Electr-o-Pura***r",
  "And Then Nothing Turned Itself Inside-Out***r",
  "There’s A Riot Going On***r",
  "Cocoa Sugar - Young Fathers",
  "White Men Are Black Men Too",
  "SlimeBall 2 - Young Nudy",
  "Nudy Land",
  "Faded In The Booth",
  "Anyways",
  "SlimeBall 3",
  "Slimeball",
  "DR. EV4L",
  "Rich Shooter",
  "Big Bad Slime (self-made compilation)",
  "sLaughter (self-made compilation)",
  "Loosies (Soulseek compilation)",
  "Sli’merre - Young Nudy & Pi’erre Bourne",
  "Barter 6 - Young Thug",
  "Slime Season",
  "Slime Season 2",
  "Slime Season 3",
  "Jeffery",
  "I’m Up",
  "So Much Fun (Deluxe)",
  "PUNK",
  "Young Martha - Young Thug / Carnage",
  "The Year of Hibernation (deluxe) - Youth Lagoon***p",
  "Wondrous Bughouse***r",
  "Savage Hills Ballroom***p",
  "Unknown Memory - Yung Lean",
  "Unknown Death 2002",
  "Warlord",
  "Stranger",
  "Frost God",
  "Poison Ivy",
  "Starz",
  "Dumbass Genius - Yung Skrrt",
  "Safe in the Hands of Love - Yves Tumor***e",
  "Heaven To A Tortured Mind***r",
  "The Asymptotical World***r",
  "Bothic - ZelooperZ",
  "Van Goghs Left Ear",
  "Dyn-O-Mite",
  "A Piece of the Geto - ZGTO (Shigeto & ZelooperZ)",
  "With Love - Zomby***e",
  "Zomby EP***e",
  "Dedication***e",
  "1000 gecs - 100 gecs***e",
  "1000 gecs and the Tree of Clues***e",
  "God Level - 03 Greedo",
  "A Brief Inquiry Into Online Relationships - The 1975***r",
  "Pretty Girls Like Trap Music - 2 Chainz",
  "Issa Album - 21 Savage",
  "i am > i was",
  "Slaughter King",
  "Spiral: From the Book of Saw",
  "Savage Mode - 21 Savage / Metro Boomin",
  "Savage Mode II",
  "Savage Mode II [CHOPPED NOT SLOPPED]",
  "Without Warning - 21 Savage / Offset / Metro Boomin",
  "Get Rich or Die Tryin’ - 50 Cent",
  "Head In The Clouds - 88 Rising"
];
